### ISSUE TITLE
This request is not supported because your node is running with state pruning. Run with --pruning=archive.

### ISSUE THREAD

**Issue by ethernomad** [mix-blockchain/acuity#1]
Acuity is not yet compatible with Parity due to https://github.com/paritytech/parity-ethereum/issues/9707

**Comment by ethernomad** [comment]
Actually we just need to use --force-sealing

**Comment by qiluge** [comment]
In the parity document ```--force-sealing
        Force the node to author new blocks as if it were always
        sealing/mining.```
So parity store all uncle block and soft-fork block and use them state at sometimes?
